name: carwashapp
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  #firebase
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  firebase_storage: ^12.3.0
  cloud_firestore: ^5.4.1

  #authentication methods
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.1.1

  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  intl_utils: ^2.8.7
  #UI
  image_picker: ^1.1.2
  flutter_svg: ^2.0.10+1
  gif_view: ^0.4.4
  intl_phone_number_input: ^0.7.4
  introduction_screen: ^3.1.14



  #local database
  shared_preferences: ^2.3.2


  #Goolge_maps
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.9.0
  location: ^6.0.2
  permission_handler: ^10.0.0
  google_maps_place_picker_mb: ^3.1.2

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_stripe: ^11.0.0
  table_calendar: ^3.1.2
 # geolocator: ^13.0.1
 # geocoding: ^3.0.0
  gap: ^3.0.1
  dio: ^5.7.0
  progress_tracker: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metrophobic-Regular.ttf
    - family: ArchivoBlack
      fonts:
        - asset: assets/fonts/ArchivoBlack-Regular.ttf

flutter_intl:
  enabled: true
  localizely:
    project_id: com.example.carwashapp
